// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZSGnyVzCdnu9OwXLp-u5p-vcDFYrU4A',
    appId: '1:1032883481959:web:dd346ef580467c856753c2',
    messagingSenderId: '1032883481959',
    projectId: 'wherewaterlogin',
    authDomain: 'wherewaterlogin.firebaseapp.com',
    storageBucket: 'wherewaterlogin.appspot.com',
    measurementId: 'G-ZQWC14M0R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0lFGZkryAXVOk8WUybUMV7QiTLpms4o',
    appId: '1:1032883481959:android:435bd5c3b895fbb66753c2',
    messagingSenderId: '1032883481959',
    projectId: 'wherewaterlogin',
    storageBucket: 'wherewaterlogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWy9bO5pu82eWisELcUr3kz0exnP41P8',
    appId: '1:1032883481959:ios:dfadd8e8d739474e6753c2',
    messagingSenderId: '1032883481959',
    projectId: 'wherewaterlogin',
    storageBucket: 'wherewaterlogin.appspot.com',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWy9bO5pu82eWisELcUr3kz0exnP41P8',
    appId: '1:1032883481959:ios:bac6b249960947d56753c2',
    messagingSenderId: '1032883481959',
    projectId: 'wherewaterlogin',
    storageBucket: 'wherewaterlogin.appspot.com',
    iosBundleId: 'com.example.projectMobile.RunnerTests',
  );
}
